language: java

script: "mvn cobertura:cobertura"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
